### ISSUE TITLE
All api get routes returning 404 not found

### ISSUE THREAD

**Issue by Previesam** [kuizuo/vitesse-nuxt3-strapi#2]
Hello thank you for the awesome starter pack, Could you please investigate the reason why I cannot access the API.

Step to reproduce;

Clone project with degit command.
cd into the Project directory run pnpm i
cd into backend run pnpm i
cd into frontend run pnpm i
cd ..
run pnpm dev

Projects started successfully and both front and backend are working except strapi api get routes saying 404 not found the same error is showing for todos route which came with this template.

**Comment by kuizuo** [comment]
I'm Sorry! I didn't do enough testing before releasing and your run failed.

I've fixed the issue at https://github.com/kuizuo/vitesse-nuxt3-strapi/commit/04c983d21bc3cbdbd66b1c577ff0d909489443b1 commit

https://github.com/kuizuo/vitesse-nuxt3-strapi/blob/7839d4739a9bdeb06897809698104a72bbdcdbb8/backend/src/api/todo/routes/todo.ts#L18

https://github.com/kuizuo/vitesse-nuxt3-strapi/blob/04c983d21bc3cbdbd66b1c577ff0d909489443b1/backend/src/api/todo/routes/todo.ts#L18
